### ISSUE TITLE
Building the model for the first time with custom dataset

### ISSUE THREAD

**Issue by pankaja0285** [soumyaiitkgp/Custom_MaskRCNN#7]
Steps followed as per your link https://medium.com/analytics-vidhya/a-simple-guide-to-maskrcnn-custom-dataset-implementation-27f7eab381f2:
 - **Step 1** - cloned your repo
 - **Step 2**: Prepare the data (90:10)
 - **Step 3**: Prepare the model.- for this I made the necessary changes to add my custom class (in my case just one)  - Running under GPU compute instance in Azure ML workspace
 -- line **91** and **140** 
 -- and also in the CustomConfig class line **71** in my case NUM_CLASSES = 1 + 1

 - ran the script 
python custom.py train --dataset="Users/pankaja_us/Custom_MaskRCNN/samples/custom/dataset/train" --weights=coco

- getting the following error -->
2020-12-18 21:52:27.922509: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1241] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10812 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0001:00:00.0, compute capability: 3.7)
Traceback (most recent call last):
  File "custom.py", line 375, in <module>
    model_dir=args.logs)
  File "/mnt/resource/batch/tasks/shared/LS_root/mounts/clusters/pankaja-gpu1/code/users/pankaja_us/Custom_MaskRCNN/mrcnn/model.py", line 1837, in __init__
    self.keras_model = self.build(mode=mode, config=config)
  File "/mnt/resource/batch/tasks/shared/LS_root/mounts/clusters/pankaja-gpu1/code/users/pankaja_us/Custom_MaskRCNN/mrcnn/model.py", line 1990, in build
    target_rois, input_gt_class_ids, gt_boxes, input_gt_masks])
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 75, in symbolic_fn_wrapper
    return func(*args, **kwargs)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/keras/engine/base_layer.py", line 489, in __call__
    output = self.call(inputs, **kwargs)
  File "/mnt/resource/batch/tasks/shared/LS_root/mounts/clusters/pankaja-gpu1/code/users/pankaja_us/Custom_MaskRCNN/mrcnn/model.py", line 664, in call
    self.config.IMAGES_PER_GPU, names=names)
  File "/mnt/resource/batch/tasks/shared/LS_root/mounts/clusters/pankaja-gpu1/code/users/pankaja_us/Custom_MaskRCNN/mrcnn/utils.py", line 820, in batch_slice
    output_slice = graph_fn(*inputs_slice)
  File "/mnt/resource/batch/tasks/shared/LS_root/mounts/clusters/pankaja-gpu1/code/users/pankaja_us/Custom_MaskRCNN/mrcnn/model.py", line 663, in <lambda>
    w, x, y, z, self.config),
  File "/mnt/resource/batch/tasks/shared/LS_root/mounts/clusters/pankaja-gpu1/code/users/pankaja_us/Custom_MaskRCNN/mrcnn/model.py", line 553, in detection_targets_graph
    positive_indices = tf.random_shuffle(positive_indices)[:positive_count]
AttributeError: module 'tensorflow' has no attribute 'random_shuffle'
azureuser@pankaja-gpu1:/mnt/resource/batch/tasks/shared/LS_root/mounts/clusters/pankaja-gpu1/code/users/pankaja_us/Custom_MaskRCNN/samples/custom$ 

Please advise. What other changes do I need to make? 
TIA
Pankaja

**Comment by soumyaiitkgp** [comment]
Hi, Pankaja. Since this is an attribute error I suggest you to try a different version of tensorflow. For me it worked with tf 1.4

**Comment by pankaja0285** [comment]
@soumyaiitkgp what version do you suggest?

**Comment by pankaja0285** [comment]
Soumya, 
  * with the issue of the attribute I was able to resolve by upgrading the **tensorflow** (your requirements.txt suggests >1.3.0), I upgraded to **2.4.0** and changed the call to tf.random.shuffle
  * then other issues occurred so I had to upgrade **h5py(2.10.0)** and **keras (2.3.0)**
  (I followed #2252 for keras and #3154 for h5py)
  * Now I get this error
  2020-12-19 19:48:24.013392: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1241] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10812 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0001:00:00.0, compute capability: 3.7)
Loading weights:  /mnt/resource/batch/tasks/shared/LS_root/mounts/clusters/pankaja-gpu1/code/users/pankaja_us/Custom_MaskRCNN/mask_rcnn_coco.h5
Traceback (most recent call last):
  File "custom.py", line 412, in <module>
    "mrcnn_bbox", "mrcnn_mask"])
  File "/mnt/resource/batch/tasks/shared/LS_root/mounts/clusters/pankaja-gpu1/code/users/pankaja_us/Custom_MaskRCNN/mrcnn/model.py", line 2135, in load_weights
    hdf5_format.load_weights_from_hdf5_group_by_name(f, layers)
  File "/anaconda/envs/azureml_py36/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 722, in load_weights_from_hdf5_group_by_name
    original_keras_version = f.attrs['keras_version'].decode('utf8')
AttributeError: 'str' object has no attribute 'decode'
azureuser@pankaja-gpu1:/mnt/resource/batch/tasks/shared/LS_root/mounts/clusters/pankaja-gpu1/code/users/pankaja_us/Custom_MaskRCNN/samples/custom$ 

Please advice.

**Comment by pankaja0285** [comment]
I was able to resolve this first time model training by using @Tom gross's blog and using the combination of Tensorflow libraries version as follows:-
numpy
scipy
Pillow
cython
matplotlib
scikit-image
**tensorflow>=2.0.0,<=2.1.0**
opencv-python
h5py
imgaug
IPython[all]
